### ISSUE TITLE
请问您的pdf是用什么软件导出的呢?

### ISSUE THREAD

**Issue by NickChilling** [iofu728/Task#5]
看到您的作业感觉样式非常好看, 冒昧问一下您的pdf是用什么软件导出的. 如有叨扰请见谅

**Comment by iofu728** [comment]
All paper was built by Latex.

you only to run 
```bash
latex main.tex
```

And I also put the latex source code in GitHub, you can refer it.

**Comment by NickChilling** [comment]
thx.
